In [2]:
#importing the modules
#import numpy n-dimensional array
import numpy as np
#import sklearn python machine learning  modules
import sklearn as sk
#import pandas dataframes
import pandas as pd
import unittest
#import matplotlib for plotting
import matplotlib.pyplot as plt
#import datasets  and linear_model from sklearn module
from sklearn import datasets, linear_model
#import Polynomial features from sklearn module
from sklearn.preprocessing import PolynomialFeatures
#import train_test_split data classification
from sklearn.model_selection import train_test_split
#import ConfusionMatrix from pandas_ml
from sklearn.metrics import confusion_matrix

In [3]:
#dataframe creation
dataframe = pd.read_csv('C:/Users/prade/Desktop/btd1_project/BTD.csv', low_memory=False) #C:\Users\prade\Desktop


In [4]:
#Dataframes for  X all the columns except class and y class columns
X = dataframe.iloc[:,:-1]
Y = dataframe['Tumor_type']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, 
test_size=1/3, random_state=0)


In [5]:
#Calculating the data
print("Train and test sizes, respectively:", len(X_train), len(Y_train), "|", len(X_test), len(Y_test))


Train and test sizes, respectively: 12 12 | 6 6


In [6]:
#logistic regression
logistic = linear_model.LogisticRegression(C=1e5)


In [7]:
logistic

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [8]:
logistic.fit(X_train, Y_train)


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [9]:
print("Using logistic Regresion Algorithm Acuracy Score: ", logistic.score(X_test, Y_test))

Using logistic Regresion Algorithm Acuracy Score:  0.5


In [10]:
Y_predicted = np.array(logistic.predict(X_test))
Y_right = np.array(Y_test)


In [11]:
Y_predicted


array([0, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
Y_test

1     0
6     0
8     0
10    1
14    1
4     0
Name: Tumor_type, dtype: int64

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_right, Y_predicted)
confusion_matrix

array([[3, 1],
       [2, 0]], dtype=int64)

In [14]:
print("Confusion matrix:",confusion_matrix)

Confusion matrix: [[3 1]
 [2 0]]


In [15]:
from sklearn.metrics import accuracy_score
accu_for_logistic=accuracy_score(Y_right,Y_predicted)
print("Acuuracy for Logistic Model is :%s"%accu_for_logistic)


Acuuracy for Logistic Model is :0.5


In [16]:
from sklearn import svm

svm_clf=svm.SVC()
svm1=svm.SVC(kernel='sigmoid',random_state = 0)

In [17]:
svm_clf.fit(X_train,Y_train)
svm1.fit(X_train,Y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
svm_pred=svm_clf.predict(X_test)
svm1_pred=svm1.predict(X_test)

In [19]:
Y_right


array([0, 0, 0, 1, 1, 0], dtype=int64)

In [20]:
svm_pred


array([0, 1, 0, 0, 1, 1], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_right,svm_pred)


array([[2, 2],
       [1, 1]], dtype=int64)

In [22]:
acc_for_svc=accuracy_score(Y_right,svm_pred)
print("Acuuracy for SVM Model is :%s"%acc_for_svc)


Acuuracy for SVM Model is :0.5


In [26]:
acc_for_svc=accuracy_score(Y_right,svm1_pred)
print("Acuuracy for SVM kernel Model is :%s"%acc_for_svc)


Acuuracy for SVM kernel Model is :0.6666666666666666


In [27]:
X_train

Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  Feature7  \
2     0.2272    0.1326    0.7439    0.9290   0.00430    0.0897    3.6046   
16    0.2925    0.1584    0.7588    0.9330   0.00570    0.0896    2.6622   
17    0.2425    0.1130    0.7700    0.9400   0.00340    0.0896    3.0000   
9     0.2689    0.0977    0.7861    0.9410   0.00068    0.0898    2.7465   
7     0.2925    0.1584    0.7588    0.9330   0.00570    0.0896    2.6622   
13    0.2272    0.0908    0.7522    0.9308   0.00340    0.0897    3.6783   
11    0.2272    0.1326    0.7439    0.9290   0.00430    0.0897    3.6046   
3     0.2442    0.1007    0.7409    0.9263   0.00320    0.0898    3.5797   
0     0.2333    0.1284    0.7491    0.9308   0.00190    0.0898    2.6632   
5     0.2558    0.0895    0.7557    0.9314   0.00250    0.0898    3.0756   
15    0.2439    0.1072    0.7310    0.9246   0.00460    0.0897    3.5484   
12    0.2750    0.1180    0.7688    0.9346   0.00460    0.0897    3.0290   

    Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  
2     0.0898    0.0080     0.9406     5.9972     0.5218     0.9700  
16    0.0898    0.0080     0.9551    13.0402     1.3124     1.2778  
17    0.0898    0.0080     0.9300     7.5890     0.7800     0.4000  
9     0.0898    0.0081     0.7186    10.9703     0.7365     0.1190  
7     0.0898    0.0080     0.9551    13.0402     1.3124     1.2778  
13    0.0898    0.0080     0.9270     5.5966     0.4004     1.0469  
11    0.0898    0.0080     0.9406     5.9972     0.5218     0.3700  
3     0.0898    0.0080     0.9234     6.2735     0.6332     0.5257  
0     0.0898    0.0081     0.8778     7.2707     0.6117    -0.0366  
5     0.0898    0.0081     0.9040     7.7971     0.5774    -0.2601  
15    0.0898    0.0081     0.9446     6.5235     0.6204     0.5030  
12    0.0898    0.0081     0.9453    13.1839     1.0085     0.2863

In [28]:
X_test

Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  Feature7  \
1     0.2717    0.0931    0.7686    0.9308    0.0024    0.0898   3.26980   
6     0.2155    0.0951    0.7378    0.9274    0.0028    0.0898   3.62830   
8     0.2341    0.1321    0.7530    0.9315    0.0035    0.0897   3.15620   
10    0.2433    0.1294    0.7606    0.9344    0.0034    0.0897   2.99490   
14    0.2517    0.0734    0.7402    0.9267    0.0035    0.0897   3.52390   
4     0.2033    0.1126    0.7554    0.9331    0.0019    0.0898   0.06549   

    Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  
1     0.0898    0.0081     0.8974     7.9567     0.8862     0.4926  
6     0.0898    0.0080     0.9132     5.3238     0.3230     1.0419  
8     0.0898    0.0080     0.9291     7.4848     0.5212    -1.0392  
10    0.0898    0.0081     0.9270     7.6801     0.6318     0.3816  
14    0.0898    0.0080     0.9284     6.5220     0.4979     1.6524  
4     0.0898    0.0080     0.8783     5.8117     0.3408     1.0010

Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  Feature7  \
2     0.2272    0.1326    0.7439    0.9290   0.00430    0.0897    3.6046   
16    0.2925    0.1584    0.7588    0.9330   0.00570    0.0896    2.6622   
17    0.2425    0.1130    0.7700    0.9400   0.00340    0.0896    3.0000   
9     0.2689    0.0977    0.7861    0.9410   0.00068    0.0898    2.7465   
7     0.2925    0.1584    0.7588    0.9330   0.00570    0.0896    2.6622   
13    0.2272    0.0908    0.7522    0.9308   0.00340    0.0897    3.6783   
11    0.2272    0.1326    0.7439    0.9290   0.00430    0.0897    3.6046   
3     0.2442    0.1007    0.7409    0.9263   0.00320    0.0898    3.5797   
0     0.2333    0.1284    0.7491    0.9308   0.00190    0.0898    2.6632   
5     0.2558    0.0895    0.7557    0.9314   0.00250    0.0898    3.0756   
15    0.2439    0.1072    0.7310    0.9246   0.00460    0.0897    3.5484   
12    0.2750    0.1180    0.7688    0.9346   0.00460    0.0897    3.0290   

    Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  
2     0.0898    0.0080     0.9406     5.9972     0.5218     0.9700  
16    0.0898    0.0080     0.9551    13.0402     1.3124     1.2778  
17    0.0898    0.0080     0.9300     7.5890     0.7800     0.4000  
9     0.0898    0.0081     0.7186    10.9703     0.7365     0.1190  
7     0.0898    0.0080     0.9551    13.0402     1.3124     1.2778  
13    0.0898    0.0080     0.9270     5.5966     0.4004     1.0469  
11    0.0898    0.0080     0.9406     5.9972     0.5218     0.3700  
3     0.0898    0.0080     0.9234     6.2735     0.6332     0.5257  
0     0.0898    0.0081     0.8778     7.2707     0.6117    -0.0366  
5     0.0898    0.0081     0.9040     7.7971     0.5774    -0.2601  
15    0.0898    0.0081     0.9446     6.5235     0.6204     0.5030  
12    0.0898    0.0081     0.9453    13.1839     1.0085     0.2863

Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  Feature7  \
1     0.2717    0.0931    0.7686    0.9308    0.0024    0.0898   3.26980   
6     0.2155    0.0951    0.7378    0.9274    0.0028    0.0898   3.62830   
8     0.2341    0.1321    0.7530    0.9315    0.0035    0.0897   3.15620   
10    0.2433    0.1294    0.7606    0.9344    0.0034    0.0897   2.99490   
14    0.2517    0.0734    0.7402    0.9267    0.0035    0.0897   3.52390   
4     0.2033    0.1126    0.7554    0.9331    0.0019    0.0898   0.06549   

    Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  
1     0.0898    0.0081     0.8974     7.9567     0.8862     0.4926  
6     0.0898    0.0080     0.9132     5.3238     0.3230     1.0419  
8     0.0898    0.0080     0.9291     7.4848     0.5212    -1.0392  
10    0.0898    0.0081     0.9270     7.6801     0.6318     0.3816  
14    0.0898    0.0080     0.9284     6.5220     0.4979     1.6524  
4     0.0898    0.0080     0.8783     5.8117     0.3408     1.0010